<?php


namespace App\AdminModule\Presenters;

use App\Model\Entity\MainSubject;
use App\Model\LogModel;
use App\Model\MainSubjectModel;

/**
 * Class BaseLogPresenter
 * @package App\AdminModule\Presenters
 */
abstract class BaseLogPresenter extends BasePresenter
{
    /**
     * @var LogModel
     * @inject
     */
    public $logModel;

	/**
	 * @var MainSubjectModel
	 * @inject
	 */
    public $mainSubjectModel;

    public function __construct()
    {
	    parent::__construct();
	    $this->addBreadcrumb('Seznam subjektů', 'MainSubject:default');
    }

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub

    }

    public function actionDefault( $main_subject_id ){
	    $this->addBreadcrumb('Logy');
	    $this->template->main_subject = $this->mainSubjectModel->find( (int)$main_subject_id );

    }
}