<?php


namespace App\AdminModule\Presenters;

/**
 * Class LogPresenter
 * @package App\AdminModule\Presenters
 */
final class LogPresenter extends BaseLogPresenter
{

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

    public function actionDefault($main_subject_id, $search_action = null, $search_name = null)
    {
        parent::actionDefault($main_subject_id);
        $this->template->logs = $this->logModel->getLogByActionAndUser( (int)$main_subject_id, $search_action, $search_name );
        $this->template->count_logs = $this->logModel->getCountLog( (int)$main_subject_id );

    }
}